name: Documentation
on:
  push:
    branches:
      - 3-better-documentation
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install the project
        run: uv sync --group docs

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Deploy
        run: uv run mkdocs gh-deploy --force
