name: PyTest
on:
  push:
    branches: [main]
    paths:
      - "tests/**"
      - "validoopsie/**"
      - ".github/**"
  pull_request:
    paths:
      - "tests/**"
      - "validoopsie/**"
jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    env:
      PYSPARK_PYTHON: python
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest tests
