name: Release Drafter

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write  # Needed for autolabeler

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.ref_name }}
          tag-name: ${{ github.ref_name }}
          config-name: 'release-drafter.yml'
          name: 'Validoopsie v${{ github.ref_name }}'
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
