name: Type tests
on:
  push:
    branches: [main, dev]
    paths:
      - "validoopsie/**"
  pull_request:
    paths:
      - "validoopsie/**"
jobs:
  mypy:
    name: Type tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pytests
        run: uv run mypy validoopsie/

